name: Docker Image

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-diagrams

    - name: Publish to Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mjdk/diagrams
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "${{ steps.extract_branch.outputs.branch }}, latest"
