name: Docker Image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file python/Dockerfile --tag python-diagrams:develop

    - name: Publish to Docker Hub Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: mujahidkhaleel/python-diagrams
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

